### PR TITLE
fix: add special handling logic for structs `KotlinCxxBridgedType`

### LINKED ISSUE #795: Nitrogen generates duplicate constructors when struct contains inside any other struct with functions
### What happened?

Nitrogen generates two identical constructors for Kotlin data classes when a struct contains a child struct that has functions, causing compilation errors in Kotlin.

### Code Example

**JavaScript/TypeScript object:**
```typescript
{
  // ... other properties
  drm: {
    // ...other properties
    getLicense: (value: string) => Promise<string>
  } 
}
```

**Generated Kotlin code:**
```kotlin
data class NativeVideoConfig
  constructor(
    val uri: String,
    val externalSubtitles: Array<NativeExternalSubtitle>?,
    val drm: NativeDrmParams?,
    val headers: Map<String, String>?
  ) {

  private constructor(uri: String, externalSubtitles: Array<NativeExternalSubtitle>?, drm: NativeDrmParams?, headers: Map<String, String>?) : this(uri, externalSubtitles, drm?.let { it } as NativeDrmParams?, headers)
}
```

The generated code contains two identical constructors, which causes Kotlin compilation to fail with duplicate constructor errors.

The issue appears to be in the `needsSpecialHandling` check within `KotlinCxxBridgedType`. When a struct is nested inside another struct and contains functions (or other types that trigger `needsSpecialHandling` to return `true`), Nitrogen incorrectly generates an additional constructor.

### Reproduction Steps
1. Create a struct with a child struct that contains a function
2. Generate Kotlin code with Nitrogen
3. Observe duplicate constructors in the generated data class
4. Attempt to compile - compilation will fail

### Summary
The `needsSpecialHandling` logic seems to be designed to handle boxed types (like `Func_std__shared_ptr_Promise_std__shared_ptr_Promise_std__string_____OnGetLicensePayload` instead of `((payload: OnGetLicensePayload) -> Promise<Promise<String>>)`), but when the function is nested inside another struct, this special handling may not be necessary and causes the duplicate constructor issue.

### Nitrogen CLI logs (with `--logLevel="debug"`)

```tsx
let me know you need this, my project have quite long logs from this 😅
```

### Nitro Specs (`.nitro.ts`)

```ts
interface Child {
  someProp: string
  someFunc: (value: string) -> Promise<string>
}

interface Base {
  child?: Child
}

export interface HybridTestObject extends HybridObject<{ android: 'kotlin' }> {
  base: Base
}
```

### Nitro Modules Version

0.27.2

### Nitrogen Version

0.27.2

### Operating system

MacOS

### Additional information

- [x] I have read and followed the [Troubleshooting Guide](https://nitro.margelo.com/docs/troubleshooting).
- [ ] I created a reproduction PR to reproduce this issue here in the nitro repo. (See [Contributing](https://nitro.margelo.com/docs/contributing) for more information)
- [x] I searched for [similar issues in this repository](https://github.com/mrousavy/nitro/issues) and found none.

### PR DESCRIPTION
**Pull request by KrzysztofMoch**
## Summary

Update logic for determining when a Kotlin type bridged to C++ requires special handling, specifically improving support for nested structs. The main changes clarify that structs do not need special handling and ensure that optionals defer to their wrapped type's requirements

fixes #795

### CODE REVIEW

**Comment by mrousavy** [comment]
added tests in https://github.com/mrousavy/nitro/pull/797

File: packages/react-native-nitro-test/nitrogen/generated/android/kotlin/com/margelo/nitro/test/HybridTestObjectSwiftKotlinSpec.kt [hunk 1]
```diff
@@ -350,14 +350,9 @@ abstract class HybridTestObjectSwiftKotlinSpec: HybridObject() {
...
   
-  abstract fun jsStyleObjectAsParameters(params: JsStyleStruct): Unit
-  
   @DoNotStrip
   @Keep
-  private fun jsStyleObjectAsParameters_cxx(params: JsStyleStruct): Unit {
-    val __result = jsStyleObjectAsParameters(params)
-    return __result
-  }
+  abstract fun jsStyleObjectAsParameters(params: JsStyleStruct): Unit
```
Comment (mrousavy) [inline packages/react-native-nitro-test/nitrogen/generated/android/kotlin/com/margelo/nitro/test/HybridTestObjectSwiftKotlinSpec.kt:355]: nice, this makes things a tiiiiiny bit faster too.
